# main menu

[[main]]
  name        = "Our Story"
  weight      = 10
  identifier  = "story"
  url         = "/story/"

[[main]]
  name        = "Programs"
  weight      = 20
  identifier  = "programs"
  url         = "/programs/"

[[main]]
  name        = "Norwin Alumni & Friends"
  weight      = 30
  identifier  = "alumni"
  url         = "https://norwinalumni.org"
  [main.params]
    external = true

[[main]]
  name        = "Distinguished Alumni"
  weight      = 35
  identifier  = "distinguished-alumni"
  url         = "https://norwinalumni.org/distinguished-alumni/"
  [main.params]
    external = true

[[main]]
  name        = "News"
  weight      = 40
  identifier  = "news"
  url         = "/news/"

# footer menu

[[footer]]
  name = "Legal Info"
  weight = 10
  identifier = "legal"
  url = "/legal/"

[[footer]]
  name = "Norwin Alumni"
  weight = 20
  identifier = "nafa"
  url = "https://norwinalumni.org"
  [footer.params]
    external = true

[[footer]]
  name = "Norwin School District"
  weight = 30
  identifier = "norwin"
  url = "https://norwinsd.org"
  [footer.params]
    external = true
