baseURL         = "https://nsdcf.org"
buildDrafts     = false
buildFuture     = false
canonifyURLs    = false
relativeURLs    = false
enableRobotsTXT = true
googleAnalytics = "UA-XXXXX-Y"
languageCode    = "en-us"
metaDataFormat  = "toml"
summaryLength   = 70
pluralizelisttitles = false
theme           = "bulma"
title           = "Norwin School District Community Foundation"
sectionPagesMenu = "main"

[params]
  description = ""
  title_abbrev = "NSDCF"

  [params.social]
    facebook        = "https://www.facebook.com/groups/NorwinAlumFriends"
    facebook_alumni = "https://www.facebook.com/groups/NorwinAlumFriends"
    twitter         = ""
    twitter_alumni  = ""

  [params.contact]
    email         = "hello@nsdcf.org"
    email_alumni  = "alumni@nsdcf.org"
    phone         = "724.861.3000"
    street        = "281 McMahon Drive"
    city          = "North Huntingdon"
    state         = "PA"
    postal        = "15642"
    newsletter_signup = ""

[[menu.main]]
  name        = "Our Story"
  weight      = 10
  identifier  = "story"
  url         = "/story"
[[menu.main]]
  name        = "Programs"
  weight      = 20
  identifier  = "programs"
  url         = "/programs"
[[menu.main]]
  name        = "Alumni"
  weight      = 30
  identifier  = "alumni"
  url         = "/alumni"
[[menu.main]]
  name        = "News"
  weight      = 40
  identifier  = "news"
  url         = "/news"
[[menu.main]]
  name        = "Get Involved"
  weight      = 50
  identifier  = "get-involved"
  url         = "/get-involved"

[[menu.footer]]
  name = "Charitable Information"
  weight = 20
  identifier = "charitable-information"
  url = "/charitable-information"
[[menu.footer]]
  name = "Privacy"
  weight = 30
  identifier = "privacy"
  url = "/privacy"
[[menu.footer]]
  name = "Norwin School District"
  weight = 40
  url = "http://www.norwinsd.org"

[sitemap]
  ChangeFreq  = ""
  Filename    = "sitemap.xml"
  Priority    = "-1"
