baseURL         = "https://nsdcf.org"
buildDrafts     = false
buildFuture     = false
canonifyURLs    = false
relativeURLs    = false
enableRobotsTXT = true
googleAnalytics = "UA-XXXXX-Y"
languageCode    = "en-us"
metaDataFormat  = "toml"
summaryLength   = 70
pluralizelisttitles = false
theme           = "bulma"
title           = "Norwin School District Community Foundation"
sectionPagesMenu = "main"
[params]
  description = ""
  facebook    = ""
  twitter     = ""

[sitemap]
  ChangeFreq  = ""
  Filename    = "sitemap.xml"
  Priority    = "-1"
