baseURL         = "https://nsdcf.org"
buildDrafts     = false
buildFuture     = false
canonifyURLs    = false

relativeURLs        = false
enableRobotsTXT     = true
googleAnalytics     = "UA-181049953-1"
languageCode        = "en-us"
metaDataFormat      = "toml"
summaryLength       = 50
pluralizeListTitles = false

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""

[outputs]
  home         = ["HTML", "RSS", "REDIR"]
  section      = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
  term         = ["HTML", "RSS"]
  page         = ["HTML"]

[outputFormats]
  [outputFormats.REDIR]
    mediatype = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[permalinks]
  news = "/news/:year/:month/:slug"

[sitemap]
  ChangeFreq  = ""
  Filename    = "sitemap.xml"
  Priority    = "-1"

[taxonomies]
  author   = "news/authors"
  category = "news/categories"
  series   = "news/series"

[blackfriday]
  # https://github.com/gohugoio/hugo/issues/2424
  hrefTargetBlank = false
  angledQuotes    = true

[imaging]
  anchor         = "smart"
  quality        = 70
  resampleFilter = "CatmullRom"

  [imaging.exif]
    disableLatLong = true
