[build]
  command = "hugo mod get github.com/nsdcf/nsdcf-shared-content@main github.com/nsdcf/nsdcf-theme@master && hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.167.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
