---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: 
  hidden: false
  default: ''
- name: date
  label: Date
  type: 
  hidden: false
  default: 
- name: draft
  label: Draft
  type: 
  hidden: false
  default: true
pages:
- content/news/distinguished-alumni-2018-nominations.md
