---
pages:
- news/join-us-for-the-second-annual-knight-of-distinguished-alumni.md
- news/distinguished-alumni-2018-nominations.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
